name: Build app

on: [push, workflow_dispatch]

env:
  CMAKE_BUILD_TYPE: Release
  DCMEDIT_RELEASE: true

jobs:
  Build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: ~\AppData\Local\vcpkg\archives
          key: vcpkg-${{ runner.os }}-${{ github.run_id }}
          restore-keys: vcpkg-${{ runner.os }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 5.15.2
          cache: true

      - name: Configure
        run: cmake -B build-output -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake .

      - name: Build
        run: |
          cmake --build build-output --config ${{ env.CMAKE_BUILD_TYPE }}
          "DCMEDIT_VERSION=$(python3 .\scripts\get_version.py)" >> $env:GITHUB_ENV

      - name: Test
        run: .\build-output\test\${{ env.CMAKE_BUILD_TYPE }}\unit-test.exe

      - name: Package application
        run: python3 .\scripts\package_windows.py .\build-output\${{ env.CMAKE_BUILD_TYPE }}\dcmedit.exe .\app-package\

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dcmedit-windows-${{ env.CMAKE_BUILD_TYPE }}-${{ env.DCMEDIT_VERSION }}
          path: .\app-package

  Build-macos:
    runs-on: macos-11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: ~/.cache/vcpkg/archives
          key: vcpkg-${{ runner.os }}-${{ github.run_id }}
          restore-keys: vcpkg-${{ runner.os }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 5.15.2
          cache: true

      - name: Configure
        run: cmake -B build-output -DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake .

      - name: Build
        run: |
          cmake --build build-output --config ${{ env.CMAKE_BUILD_TYPE }}
          echo "DCMEDIT_VERSION=$(python3 ./scripts/get_version.py)" >> $GITHUB_ENV

      - name: Test
        run: ./build-output/test/unit-test

      - name: Package application
        run: python3 ./scripts/package_macos.py ./build-output/dcmedit.app ./app-package/

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dcmedit-macos-${{ env.CMAKE_BUILD_TYPE }}-${{ env.DCMEDIT_VERSION }}
          path: ./app-package

  Build-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: ~/.cache/vcpkg/archives
          key: vcpkg-${{ runner.os }}-${{ github.run_id }}
          restore-keys: vcpkg-${{ runner.os }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 5.15.2
          cache: true

      - name: Configure
        run: CXX=g++-10 cmake -B build-output -DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake .

      - name: Build
        run: |
          cmake --build build-output --config ${{ env.CMAKE_BUILD_TYPE }}
          echo "DCMEDIT_VERSION=$(python3 ./scripts/get_version.py)" >> $GITHUB_ENV

      - name: Test
        run: ./build-output/test/unit-test

      - name: Package application
        run: |
          wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage -O ~/linuxdeployqt
          chmod a+x ~/linuxdeployqt
          PATH=$PATH:~
          python3 ./scripts/package_linux.py ./build-output/dcmedit ./app-package/

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dcmedit-linux-${{ env.CMAKE_BUILD_TYPE }}-${{ env.DCMEDIT_VERSION }}
          path: ./app-package
