name: Build app

on: [push, workflow_dispatch]

env:
  CMAKE_BUILD_TYPE: Release

jobs:
  Build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Cache DCMTK
        uses: actions/cache@v3
        with:
          path: ~\AppData\Local\vcpkg\archives
          key: ${{ runner.os }}-dcmtk

      - name: Install DCMTK
        run: vcpkg install dcmtk:x64-windows

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-qt

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Configure
        run: cmake -B build-output -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake .

      - name: Build
        run: cmake --build build-output --config ${{ env.CMAKE_BUILD_TYPE }}

      - name: Test
        run: .\build-output\test\${{ env.CMAKE_BUILD_TYPE }}\test-runner.exe

      - name: Package application
        run: python3 .\scripts\package_windows.py .\build-output\${{ env.CMAKE_BUILD_TYPE }}\dcmedit.exe .\app-package\

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-${{ env.CMAKE_BUILD_TYPE }}
          path: .\app-package

  Build-macos:
    runs-on: macos-10.15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Cache DCMTK
        uses: actions/cache@v3
        with:
          path: ~/.cache/vcpkg/archives
          key: ${{ runner.os }}-dcmtk

      - name: Install DCMTK
        run: vcpkg install dcmtk:x64-osx

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-qt

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Configure
        run: cmake -B build-output -DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake .

      - name: Build
        run: cmake --build build-output --config ${{ env.CMAKE_BUILD_TYPE }}

      - name: Test
        run: ./build-output/test/test-runner

      - name: Package application
        run: python3 ./scripts/package_macos.py ./build-output/dcmedit.app ./app-package/

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-${{ env.CMAKE_BUILD_TYPE }}
          path: ./app-package

  Build-linux:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Cache DCMTK
        uses: actions/cache@v3
        with:
          path: ~/.cache/vcpkg/archives
          key: ${{ runner.os }}-dcmtk

      - name: Install DCMTK
        run: vcpkg install dcmtk:x64-linux

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-qt

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Configure
        run: CXX=g++-10 cmake -B build-output -DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake .

      - name: Build
        run: cmake --build build-output --config ${{ env.CMAKE_BUILD_TYPE }}

      - name: Test
        run: ./build-output/test/test-runner

      - name: Package application
        run: |
          wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage -O ~/linuxdeployqt
          chmod a+x ~/linuxdeployqt
          PATH=$PATH:~
          python3 ./scripts/package_linux.py ./build-output/dcmedit ./app-package/

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-${{ env.CMAKE_BUILD_TYPE }}
          path: ./app-package
